title: Paciran Lamongan
description: "Paciran itu... Yo ngono iku cak!"
tagline: "Truth, Faith & Fake"
url: "https://www.paciran.com"
sass:
 sass_dir: _sass
navigation:
 - text: Home
   url: /
 - text: About
   url: /about
 - text: Style Guide
   url: /style-guide
 - text: Archive
   url: /tags/
# author detail
author_name: Jon Mukidi
author_bio: Jon Mukidi is a designer, photographer, speaker, author of a couple of blogs and the founder of the some-kind-of-stupidity
author_url: https://www.knoacc.org
author_location: Somewhere, Out-there
author_image: /images/authorimage.png
# comments
disqus: paciran1
# banner ads
banner_url: https://safelink.knoacc.org
banner_image: images/banner.jpg
# adsbygoogle
ads:
 pub: "ca-pub-8526606076277673"
 slot: "8128278337"

# header_slot

# footer_slot

# social
instagram_username: ph4t3
# paginate
paginate: 6
paginate_path: /blog/page:num/

plugins:
 - jekyll-paginate
 - jekyll-seo-tag
