title: "Paciran Lamongan"
description: "Ayem Tentrem Kerto Raharjo
tagline: "Thoughts, stories and ideas."
# baseurl:
sass:
 sass_dir: _sass
url: "https://www.paciran.com"
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Style Guides
  url: /style-guide/
- text: Archives
  url: /tags/
# The shortname for your Disqus site to enable comments.
# disqus:

# Author information - author info at the bottom of the post
author_name: "John Doe"
author_bio: "John is a designer, photographer, speaker, author of a couple of books about typography and the founder of photo magazine Curious."
author_url:  "https://www.knoacc.org"
author_location: "Somewhere, Out-there"
author_image: /images/authorimage.png
# Sidebar Add banner
banner_url: "https://safelink.knoacc.org
banner_image: images/banner.jpg
# Sidebar newsletter widget - add your form action url for MailChimp signup form here
# mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"
# Social links in the site footer
twitter_username: "username"
facebook_username: "KnoAcc"
#googleplus_username: "+username"
#github_username: "username"
#codepen_username: "username"
#dribbble_uername: "username"
#medium_username: "@username"
instagram_username: "ph4t3"
#pinterest_username: "username"
#linkedin_username: "username"
# http://jekyllrb.com/docs/pagination/
paginate: 6
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]
permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
    
