title: Paciran Lamongan
description: "Paciran itu; yo ngono iku cak, Mesuwur!"
tagline: "Truth, Faith & Fake"
url: "https://www.paciran.com"
sass:
 sass_dir: _sass
navigation:
 - text: Home
   url: /
 - text: About
   url: /about
 - text: Style Guide
   url: /style-guide
 - text: Archive
   url: /tags/
   text: Kontak
   url: /kontak
# author detail
author_name: Jon Mukidi
author_bio: Jon Mukidi is a real-designer, not-photographer, nyocot-er, author of a couple of blogs and the founder of the some-kind-of-stupidity
# author_url: https://www.knoacc.org
author_location: Somewhere, Out-there
author_image: /images/authorimage.png
# comments
disqus: paciran1
# banner ads
banner_url: /kontak
banner_image: images/banner.jpg

# social
instagram_username: ph4t3
twitter_username: idlohulhaq
facebook_username: nasyrih
# paginate
paginate: 6
paginate_path: /blog/page:num/

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..5
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

plugins:
 - jekyll-paginate
 - jekyll-paginate-category
 - jekyll-seo-tag
 - jekyll-tagging
 - jekyll-tagging-related_posts
 - jemoji
whitelists:
 - jekyll-paginate
 - jekyll-paginate-category
 - jekyll-seo-tag
 - jekyll-tagging
 - jekyll-tagging-related_posts
 - jemoji
# - amp-jekyll
#amp
#ampdir: /amp

compress_html:
  clippings: all
  comments: all
  blanklines: true
  endings: all
  startings: [head, html, body]
