site: Paciran Lamongan
description: "Paciran itu... Yo ngono iku cak!"
tagline: "Truth, Faith & Fake"
url: "https://www.paciran.com"
sass:
 sass_dir: _sass
navigation:
 - text: Home
   url: /
 - text: About
   url: /about/
 - text: Style Guide
   url: /style-guide/
 - text: Archive
   url: /tags/
# author detail
author_name: Jon Mukidi
author_bio: Jon Mukidi is a designer, photographer, speaker, author of a couple of books about typography and the founder of photo magazine Curious
author_url: https://www.knoacc.org
author_location: Somewhere, Out-there
author_image: /images/authorimage.png
# banner ads
banner_url: https://safelink.knoacc.org
banner_image: images/banner.jpg
# social
instagram_username: ph4t3
# paginate
paginate: 6
paginate_path: /blog/page:num/

plugins:
 - jekyll-paginate
