title: Paciran Lamongan
description: "Paciran itu; yo ngono iku cak, Mesuwur!"
tagline: "Truth, Faith & Fake"
url: "https://www.paciran.com"
sass:
 sass_dir: _sass
navigation:
 - text: Home
   url: /
 - text: About
   url: /about
 - text: Style Guide
   url: /style-guide
 - text: Archive
   url: /tags/
   text: Kontak
   url: /kontak
# author detail
author_name: Jon Mukidi
author_bio: Jon Mukidi is a real-designer, not-photographer, nyocot-er, author of a couple of blogs and the founder of the some-kind-of-stupidity
# author_url: https://www.knoacc.org
author_location: Somewhere, Out-there
author_image: /images/authorimage.png
# comments
disqus: paciran1
# banner ads
banner_url: https://safelink.knoacc.org
banner_image: images/banner.jpg

# social
instagram_username: ph4t3
# paginate
paginate: 6
paginate_path: /blog/page:num/

plugins:
 - jekyll-paginate
 - jekyll-paginate-category
 - jekyll-seo-tag
 - jekyll-tagging
 - jekyll-tagging-related_posts
 - jemoji
# - amp-jekyll
#amp
#ampdir: /amp

compress_html:
  clippings: all
  comments: all
  blanklines: true
  endings: all
  startings: [head, html, body]
