title: Paciran ❤ Lamongan
description: "Paciran bukan di Tuban, tapi di pesisir Lamongan"
tagline: "Truth, Faith & Fakes"
url: "https://www.paciran.com"
sass:
 sass_dir: _sass
navigation:
 - text: Home
   url: /
 - text: About
   url: /about
 - text: Style Guide
   url: /style-guide
 - text: Archive
   url: /tags/
   text: Kontak
   url: /kontak
# author detail
author:
  name: Jon Mukidi
  bio: Jon Mukidi is a real-designer, not-photographer, nyocot-er, author of a couple of blogs and the founder of the some-kind-of-stupidity
  uri: https://www.knoacc.org
  location: Somewhere, Out-there
  avatar: images/authorimage.png
  facebook: nasyrih
  twitter: idlohulhaq
  
# comments
disqus: paciran1
# banner ads
banner_url: https://www.paciran.com/kontak
banner_image: https://i0.wp.com/www.paciran.com/images/banner.jpg?resize=320,300

postad_url: /kontak
postad_image: https://i1.wp.com/www.paciran.com/images/banner.jpg?resize=300,250
postad_alt: Pasang Iklan Bulanan

social:
# instagram: paciranmesuwur
  twitter: idlohulhaq
  facebook: paciran.com
# paginate
paginate: 6
paginate_path: /blog/page:num/

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: false
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..5
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
# default
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: mukidi
      
plugins:
 - jekyll-paginate
 - jekyll-paginate-category
 - jekyll-seo-tag
 - jekyll-tagging
 - jekyll-tagging-related_posts

compress_html:
#  clippings: all
  comments: all
  blanklines: true
 # endings: all
 # startings: [head, html, body]
